export const SportsEvents = [
  // October 18th - Semi-finals, Quarters, Knockouts
  {
    id: 1,
    heading: "Football Semi-Final 1",
    teams: "IIT BHU vs IIT Bombay",
    location: "Main Ground, IIT BHU",
    date: "2024-10-18",
    time: "17:00",
    sport: "Football",
    description: "Semi-final match of the Football Championship between IIT BHU and IIT Bombay.",
  },
  {
    id: 2,
    heading: "Basketball Quarter-Final 1",
    teams: "IIT Delhi vs NIT Trichy",
    location: "Indoor Stadium, IIT BHU",
    date: "2024-10-18",
    time: "10:00",
    sport: "Basketball",
    description: "Quarter-final of the Basketball Tournament with IIT Delhi facing NIT Trichy.",
  },
  {
    id: 3,
    heading: "Cricket Knockout Round",
    teams: "BITS Pilani vs IIT Kanpur",
    location: "Cricket Ground, IIT BHU",
    date: "2024-10-18",
    time: "14:00",
    sport: "Cricket",
    description: "Knockout round of the Cricket Championship featuring BITS Pilani and IIT Kanpur.",
  },
  {
    id: 4,
    heading: "Tennis Knockout Round",
    teams: "IIT Roorkee vs SRM University",
    location: "Tennis Courts, IIT BHU",
    date: "2024-10-18",
    time: "12:00",
    sport: "Tennis",
    description: "Knockout round of the Tennis Invitational featuring IIT Roorkee and SRM University.",
  },
  {
    id: 5,
    heading: "Chess Semi-Final 1",
    teams: "IIT Madras vs IIT BHU",
    location: "Chess Room, IIT BHU",
    date: "2024-10-18",
    time: "10:00",
    sport: "Chess",
    description: "Semi-final of the Chess Grandmasters tournament with IIT Madras facing IIT BHU.",
  },
  {
    id: 6,
    heading: "Weightlifting Semi-Final 1",
    teams: "IIT Patna vs IIT BHU",
    location: "Weightlifting Hall, IIT BHU",
    date: "2024-10-18",
    time: "13:00",
    sport: "Weightlifting",
    description: "Semi-final of the Weightlifting Challenge between IIT Patna and IIT BHU.",
  },
  {
    id: 7,
    heading: "Swimming Semi-Final 1",
    teams: "IIT Roorkee vs NIT Trichy",
    location: "Swimming Pool, IIT BHU",
    date: "2024-10-18",
    time: "07:00",
    sport: "Swimming",
    description: "Semi-final of the Swimming Gala with IIT Roorkee competing against NIT Trichy.",
  },
  {
    id: 8,
    heading: "Martial Arts Knockout Round",
    teams: "IIT BHU vs IIT Indore",
    location: "Martial Arts Arena, IIT BHU",
    date: "2024-10-18",
    time: "11:00",
    sport: "Martial Arts",
    description: "Knockout round of the Martial Arts Championship featuring IIT BHU and IIT Indore.",
  },
  {
    id: 9,
    heading: "Volleyball Semi-Final 1",
    teams: "IIT Madras vs IIM Ahmedabad",
    location: "Volleyball Court, IIT BHU",
    date: "2024-10-19",
    time: "09:00",
    sport: "Volleyball",
    description: "Semi-final match of the Volleyball Championship between IIT Madras and IIM Ahmedabad.",
  },
  {
    id: 10,
    heading: "Kabaddi Quarter-Final 1",
    teams: "IIT BHU vs MNIT Jaipur",
    location: "Kabaddi Arena, IIT BHU",
    date: "2024-10-19",
    time: "16:00",
    sport: "Kabaddi",
    description: "Quarter-final of the Kabaddi Championship with IIT BHU competing against MNIT Jaipur.",
  },
  {
    id: 11,
    heading: "Table Tennis Semi-Final 1",
    teams: "IIT Kharagpur vs IISc Bangalore",
    location: "Indoor Arena, IIT BHU",
    date: "2024-10-19",
    time: "11:00",
    sport: "Table Tennis",
    description: "Semi-final match of the Table Tennis Masters featuring IIT Kharagpur and IISc Bangalore.",
  },
  {
    id: 12,
    heading: "Badminton Knockout Round",
    teams: "IIT BHU vs VIT Vellore",
    location: "Badminton Hall, IIT BHU",
    date: "2024-10-19",
    time: "09:30",
    sport: "Badminton",
    description: "Knockout round of the Badminton League with IIT BHU taking on VIT Vellore.",
  },
  {
    id: 13,
    heading: "Hockey Semi-Final 1",
    teams: "IIT Bombay vs IIT Guwahati",
    location: "Hockey Field, IIT BHU",
    date: "2024-10-19",
    time: "15:00",
    sport: "Hockey",
    description: "Semi-final of the Hockey Championship between IIT Bombay and IIT Guwahati.",
  },
  {
    id: 14,
    heading: "Squash Knockout Round",
    teams: "BITS Pilani vs IIT Hyderabad",
    location: "Squash Courts, IIT BHU",
    date: "2024-10-19",
    time: "14:00",
    sport: "Squash",
    description: "Knockout round of the Squash Invitational featuring BITS Pilani and IIT Hyderabad.",
  },
  {
    id: 15,
    heading: "Athletics Knockout Round",
    teams: "NIT Surathkal vs IIT Gandhinagar",
    location: "Athletics Track, IIT BHU",
    date: "2024-10-19",
    time: "08:00",
    sport: "Athletics",
    description: "Knockout round of the Athletics Meet featuring NIT Surathkal and IIT Gandhinagar.",
  },
  {
    id: 16,
    heading: "Football Semi-Final 2",
    teams: "IIT Kanpur vs IIT Madras",
    location: "Main Ground, IIT BHU",
    date: "2024-10-18",
    time: "19:00",
    sport: "Football",
    description: "Second semi-final match of the Football Championship between IIT Kanpur and IIT Madras.",
  },
  {
    id: 17,
    heading: "Basketball Quarter-Final 2",
    teams: "IIT Bombay vs NIT Calicut",
    location: "Indoor Stadium, IIT BHU",
    date: "2024-10-18",
    time: "12:00",
    sport: "Basketball",
    description: "Quarter-final of the Basketball Tournament with IIT Bombay facing NIT Calicut.",
  },
  {
    id: 18,
    heading: "Cricket Knockout Round",
    teams: "IIT BHU vs NIT Trichy",
    location: "Cricket Ground, IIT BHU",
    date: "2024-10-19",
    time: "14:00",
    sport: "Cricket",
    description: "Knockout round of the Cricket Championship featuring IIT BHU and NIT Trichy.",
  },
  {
    id: 19,
    heading: "Tennis Knockout Round",
    teams: "IIT Delhi vs IIT Ropar",
    location: "Tennis Courts, IIT BHU",
    date: "2024-10-19",
    time: "16:00",
    sport: "Tennis",
    description: "Knockout round of the Tennis Invitational featuring IIT Delhi and IIT Ropar.",
  },
  {
    id: 20,
    heading: "Chess Semi-Final 2",
    teams: "IIT Bombay vs IIT Guwahati",
    location: "Chess Room, IIT BHU",
    date: "2024-10-19",
    time: "15:00",
    sport: "Chess",
    description: "Semi-final of the Chess Grandmasters tournament with IIT Bombay facing IIT Guwahati.",
  },

  // Finals on October 20th
  {
    id: 21,
    heading: "Football Final",
    teams: "IIT BHU vs IIT Bombay",
    location: "Main Ground, IIT BHU",
    date: "2024-10-20",
    time: "17:00",
    sport: "Football",
    description: "The grand final of the Football Championship between IIT BHU and IIT Bombay.",
  },
  {
    id: 22,
    heading: "Basketball Final",
    teams: "IIT Delhi vs NIT Trichy",
    location: "Indoor Stadium, IIT BHU",
    date: "2024-10-20",
    time: "10:00",
    sport: "Basketball",
    description: "The final match of the Basketball Tournament with IIT Delhi facing NIT Trichy.",
  },
  {
    id: 23,
    heading: "Cricket Final",
    teams: "BITS Pilani vs IIT Kanpur",
    location: "Cricket Ground, IIT BHU",
    date: "2024-10-20",
    time: "14:00",
    sport: "Cricket",
    description: "The final of the Cricket Championship featuring BITS Pilani and IIT Kanpur.",
  },
  {
    id: 24,
    heading: "Volleyball Final",
    teams: "IIT Madras vs IIM Ahmedabad",
    location: "Volleyball Court, IIT BHU",
    date: "2024-10-20",
    time: "09:00",
    sport: "Volleyball",
    description: "The final match of the Volleyball Championship between IIT Madras and IIM Ahmedabad.",
  },
  {
    id: 25,
    heading: "Tennis Final",
    teams: "IIT Roorkee vs SRM University",
    location: "Tennis Courts, IIT BHU",
    date: "2024-10-20",
    time: "12:00",
    sport: "Tennis",
    description: "The final of the Tennis Invitational with IIT Roorkee competing against SRM University.",
  },
  {
    id: 26,
    heading: "Kabaddi Final",
    teams: "IIT BHU vs MNIT Jaipur",
    location: "Kabaddi Arena, IIT BHU",
    date: "2024-10-20",
    time: "16:00",
    sport: "Kabaddi",
    description: "The final of the Kabaddi Championship featuring IIT BHU and MNIT Jaipur.",
  },
  {
    id: 27,
    heading: "Table Tennis Final",
    teams: "IIT Kharagpur vs IISc Bangalore",
    location: "Indoor Arena, IIT BHU",
    date: "2024-10-20",
    time: "11:00",
    sport: "Table Tennis",
    description: "The final match of the Table Tennis Masters between IIT Kharagpur and IISc Bangalore.",
  },
  {
    id: 28,
    heading: "Badminton Final",
    teams: "IIT BHU vs VIT Vellore",
    location: "Badminton Hall, IIT BHU",
    date: "2024-10-20",
    time: "14:00",
    sport: "Badminton",
    description: "The final of the Badminton League with IIT BHU taking on VIT Vellore.",
  },
  {
    id: 29,
    heading: "Hockey Final",
    teams: "IIT Bombay vs IIT Guwahati",
    location: "Hockey Field, IIT BHU",
    date: "2024-10-20",
    time: "15:00",
    sport: "Hockey",
    description: "The grand final of the Hockey Championship between IIT Bombay and IIT Guwahati.",
  },
  {
    id: 30,
    heading: "Squash Final",
    teams: "BITS Pilani vs IIT Hyderabad",
    location: "Squash Courts, IIT BHU",
    date: "2024-10-20",
    time: "14:00",
    sport: "Squash",
    description: "The final of the Squash Invitational featuring BITS Pilani and IIT Hyderabad.",
  },
];